### ISSUE TITLE
mysqlite.db location

### ISSUE THREAD

**Issue by Imaginativeone** [cytech-services/electron-sqlite-vue-tailwind#1]
In your repo, the path of the sqlite db is: /Users/imaginativeone/Library/Application Support/electron-sqlite-vue-tailwind/mysqlite.db

How do I change this folder to one that is local to the repo files?

This is the path I'm after:
/Users/imaginativeone/Documents/Software-Development/Electron/electron-sqlite-vue-tailwind/databases/mysqlite.db

**Comment by cytech-services** [comment]
@Imaginativeone please check the updated [README.md](https://github.com/cytech-services/electron-sqlite-vue-tailwind/blob/master/README.md) for new configuration via an environment file. Please let me know if this helps you achieve what you wanted.
